MiniFb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("SocialApp.urls")),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SocialApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django_email_verification import urls as mail_urls


app_name = 'socialapp'
urlpatterns = [
    path('', views.registerPage),
    path('login/', views.userLogin, name="login"),
    path('registration_page/', views.registerPage, name='register'),
    path('home/', views.home, name='home'),
    path('logout/', views.logoutUser, name="logout"),
    path('newpost/', views.newPost, name="newpost"),
    path('userpostspage/', views.userPostsPage, name='userposts'),
    path('postdetailpage/<int:id>', views.postdetail, name='postdetail'),
    path('updatepost/<int:id>/', views.updatePost, name='updatepost'),
    path('deletepost/<int:id>/', views.deletePost, name='deletepost'),
    path('verifylogin/', views.verifyEmail),

]

SocialApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Users(AbstractUser):
    class Meta:
        verbose_name = "CustomUser"
        verbose_name_plural = "CustomUsers"


class BlogPost(models.Model):
    title = models.CharField(max_length=300)
    description = models.CharField(max_length=1000)
    # image = models.ImageField(upload_to='profilePictures')
    image = models.ImageField()
    user = models.ForeignKey(Users, on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return self.title

SocialApp/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Users
from django.forms import ModelForm
from django import forms

class CreateUserForm(UserCreationForm):
    class Meta:
        model = Users
        fields = ['username', 'email', 'password1', 'password2']

SocialApp/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from MiniFb import settings
from .forms import CreateUserForm
from .models import *
from django.core.mail import send_mail
from MiniFb.settings import *

def index(request):
    return HttpResponse("Testing")


def registerPage(request):
    if request.user.is_authenticated:
        return redirect('socialapp:userposts')
    else:
        form = CreateUserForm()
        context = {}
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                subject = 'Email Verification'
                message = 'http://127.0.0.1:8000/verifylogin/?token=1234'
                form.save()
                recepient = request.POST.get('email')
                send_mail(subject,
                          message, EMAIL_HOST_USER, [recepient], fail_silently=False)
                return redirect('socialapp:register')
        context['form'] = form
        return render(request, 'register.html', context)

@login_required
def home(request):
    posts = BlogPost.objects.all()
    return render(request, 'home.html', {'posts': posts})


def userLogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        usr = authenticate(request, username=username, password=password)
        if usr is not None:
            login(request, usr)
            return redirect('socialapp:userposts')
        else:
            messages.info(request, 'Username OR password is incorrect')

    context = {}
    return render(request, 'login.html', context)

@login_required
def logoutUser(request):
    logout(request)
    return redirect('socialapp:login')


@login_required
def newPost(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        image = request.FILES.get('picture')
        description = request.POST.get('description')
        post = BlogPost(title=title, image=image, description=description, user=request.user)
        post.save()
        return redirect('socialapp:userposts')

    context = {}
    return render(request, 'new_post.html', context)

@login_required
def userPostsPage(request):
    posts = BlogPost.objects.filter(user=request.user)
    context = {'posts': posts, 'media_url': settings.MEDIA_URL}
    return render(request, 'user_posts.html', context)

@login_required
def postdetail(request, id):
    post = BlogPost.objects.filter(id=id)
    context = {'post': post, 'media_url': settings.MEDIA_URL}
    return render(request, 'post_detail.html', context)

@login_required
def updatePost(request, id):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        try:
            image = request.FILES.get('picture')
            BlogPost.objects.filter(id=id).update(title=title, image=image, description=description)
        except:
            BlogPost.objects.filter(id=id).update(title=title, description=description)

        return redirect('socialapp:userposts')

    post = BlogPost.objects.filter(id=id)
    context = {'post': post, 'media_url': settings.MEDIA_URL}
    return render(request, 'update_post.html', context)

@login_required
def deletePost(request, id):
    BlogPost.objects.filter(id=id).delete()
    return redirect('socialapp:userposts')



def verifyEmail(request):
    key =1234
    token = request.GET.get('token')
    if int(token) == key:
        return redirect('socialapp:login')
    else:
        return HttpResponse('invalid token')

SocialApp/templates/confirm_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirmation</title>
    <style>
        body{ color: blue; }
    </style>
</head>
<body>
    {% if success %}
        You have confirmed your account!
    {% else %}
        Error, invalid token!
    {% endif %}
</body>
</html>

SocialApp/templates/login.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;

		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'socialapp:register' %}" class="ml-2">Sign Up</a>
					</div>

				</div>
			</div>
		</div>
	</div>
</body>

</html>

SocialApp/templates/mail_body.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        h1{ color: blue; }
    </style>
</head>
    <body>
        <h1>You are almost there!</h1><br>
        <h2>Please click <a href="{{ link }}">here</a> to confirm your account</h2>
    </body>
</html>

SocialApp/templates/main.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">

</head>
<body>
	{%  include 'navbar.html' %}
	<div class="container-fluid">
	{% block content %}



	{% endblock %}
    </div>
	<hr>
	<h5>copyright&copy; @ Argon</h5>
	
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

SocialApp/templates/navbar.html
{% load static %}

<style>
  .hello-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
 <img src="{% static 'img.png' %}">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'socialapp:userposts' %}">My Posts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'socialapp:newpost' %}">Post a Memory</a>
      </li>
    </ul>
  </div>

  <span class="hello-msg">Hello, {{request.user}}</span>
<!--  <span ><a  class="hello-msg" href="{% url 'socialapp:register' %}">Register</a></span>-->
  <span ><a  class="hello-msg" href="{% url 'socialapp:logout' %}">Logout</a></span>

</nav>

SocialApp/templates/new_post.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}

<meta charset="UTF-8">
<head>
    <style>
        .btn{
        background-color: orange;
        border: 2px solid black;
        margin: 30px;
        }

        .post{
        backgroud-color: yellow;
        border: 2px solid black;
        margin: 10px;
        }
    </style>
</head>
<title>New Post</title>
<div class="post">
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <br>
    <label>Title</label>
    <input type="text" name="title">
    <br><br>

    <input type="file" name="picture">
    <br><br>

    <label>Description</label>
    <textarea name="description" rows="4" cols="50"></textarea>
    <br><br>
    <input type="submit" value="Post" class="btn">
</form>
</div>

{% endblock %}

SocialApp/templates/post_detail.html
<!DOCTYPE html>
<html>

<head>
    <title>Post details</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		.detail-div{
		    margin:10px;
		    padding: 10px;
		}
        .clear{
            both:clear;
        }
        div{
            display:block;
        }
    </style>
</head>

<body>
<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
                {% for p in post%}
                <div class="d-flex justify-content-center detail-div" style="float:left" style="display: block;">
                    <h4>{{ p.title }}</h4>
                </div>
                <div class="d-flex justify-content-center detail-div" style="float:left" style="display: block;">
                    <img src="{{media_url}}/{{p.image}}" style="width:200px; height:200px;">
                </div>
                <br>
                <p>
                    {{p.description}}
                </p>
                {%endfor%}
        </div>
    </div>
</div>
</body>
</html>

SocialApp/templates/register.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>



				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>

					</form>
				</div>

				{{form.errors}}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'socialapp:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

SocialApp/templates/update_post.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}

<meta charset="UTF-8">
<title>New Post</title>
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {%for p in post%}
    <br>
    <label>Title</label>
    <input type="text" name="title" value="{{p.title}}">
    <br><br>
<!--    <img id="img" src="{{media_url}}/{{p.image}}" style="width:200px; height:200px;">-->
    <br>
    <input type="file" name="picture">
    <br><br>

    <label>Description</label>
    <textarea name="description" rows="4" cols="50">{{p.description}}</textarea>
    {%endfor%}
    <br><br>
    <input type="submit" value="Update">
</form>


{% endblock %}

<script>

</script>

SocialApp/templates/user_posts.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}
<head>
    <style>
        button{
            width: 100px;
            background-color:orange;
            color:white;
            float:right;
            margin:10px;
            margin-left: -8px;
        }
    </style>
</head>
    <title>Posts</title>

    <div id="user-name">
        <h4>My Posts</h4>

    </div>

<div class="row">
	<div class="col-md-7">
		<hr>
		<div class="card card-body">
        {%for p in posts %}
            <table style="border: 2px solid green; padding: 10px; margin: 20px;">
                <tr>
                    <td>
                        <h4>{{p.title}}</h4>
                        <br>
                        <p>
                            {{p.description}}
                    </td>
                    <td>
                        <img src="{{media_url}}/{{p.image}}" style="width:200px; height:200px; float:right;">
                    </td>
                    <td>
                        <button type="submit" onclick="location.href = '{% url 'socialapp:postdetail' p.id %}'">View</button><br>
                        <button type="submit" onclick="location.href = '{% url 'socialapp:updatepost' p.id %}'">Update</button><br>
                        <button type="submit" onclick="location.href = '{% url 'socialapp:deletepost' p.id %}'">Delete</button><br>

                    </td>

                </tr>
            </table>

        {%endfor%}
    </div>
    </div>
</div>

{% endblock %}